untracked_devices : track packages required for microdroid
Without these the build fails and throws the below error.

error: packages/modules/Virtualization/microdroid/signature/Android.bp:41:1: "mk_payload" depends on undefined module "libcdisk_spec"
error: packages/modules/Virtualization/microdroid/signature/Android.bp:41:1: "mk_payload" depends on undefined module "libimage_aggregator"
error: packages/modules/Virtualization/microdroid/signature/Android.bp:41:1: "mk_payload" depends on undefined module "libcuttlefish_fs"
error: packages/modules/Virtualization/microdroid/signature/Android.bp:41:1: "mk_payload" depends on undefined module "libcuttlefish_utils"